### Data Types

List : Mirip array biasa \
Tuple : Tidak bisa mengganti isi data. \
Set : Mirip list tapi isi datanya harus unique \
Dictionary : Isinya format {key : value}

In [14]:
myList = list()
myList.append(5)
print(myList)

myTuple = (3,4,5)
print(myTuple)

mySet = {3,4,5,5}
print(mySet)

myDictionary = {"name"  : "Felix"}
print(myDictionary["name"])

myListDictionary = [
    {"name" : "Felix", "class" : "LA05"}, 
    {"name" : "Udin", "class" : "LA06"}
]

print(myListDictionary[0]["name"])

# List Comprehension
i = [x for x in range(101)]
print(i)

[5]
(3, 4, 5)
{3, 4, 5}
Felix
Felix
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


In [43]:
import numpy as np

my1DArray = np.array([3,4,1])
my2DArray = np.array([
    [3,4,5],
    [6,7,8]
])
print(my1DArray)
print(my2DArray)

[3 4 1]
[[3 4 5]
 [6 7 8]]


### Read Image

imread -> Baca gambar\
imshow -> nampilin gambar\
waitKey > nunggu key untuk close

In [28]:
import random
from tkinter import N
import cv2

cat = cv2.imread("./cat.jpg", 3)
cat = cv2.resize(cat, (int(cat.shape[1] * 0.5), int( cat.shape[0] * 0.5)), interpolation=cv2.INTER_AREA)

In [31]:
divider = int(cat.shape[0] / 3)
for i in range(50) :
    string = f"image{i + 1}.jpg"  
    k = 0
    for j in range(0, 3) :
        k += divider
        cat[:, :k, j] = random.randint(0, 255)
    k = 0
    cv2.destroyAllWindows()
    cv2.imwrite(string, cat)

In [32]:
string = f"image{i + 1}.jpg"  
k = 0
for j in range(0, 3) :
    k += divider
    cat[:, :k, j] = random.randint(0, 255)
k = 0
cv2.destroyAllWindows()
cv2.imwrite(string, cat)

True